

NBATeamDict = {}

NBATeamDict[1] = ["Atlanta Hawks", "Hawks", True, "AtlantaHawks.png"]
NBATeamDict[2] = ["Boston Celtics", "Celtics", True, "BostonCeltics.png"]
NBATeamDict[4] = ["Brooklyn Nets", "Nets", True, "BrooklynNets.png"]
NBATeamDict[5] = ["Charlotte Hornets", "Hornets", True, "CharlotteHornets.png"]
NBATeamDict[6] = ["Chicago Bulls", "Bulls", True, "ChicagoBulls.png"]
NBATeamDict[7] = ["Cleveland Cavaliers", "Cavaliers", True, "ClevelandCavaliers.png"]
NBATeamDict[8] = ["Dallas Mavericks", "Mavericks", False, "DallasMavericks.png"]
NBATeamDict[9] = ["Denver Nuggets", "Nuggets", False, "DenverNuggets.png"]
NBATeamDict[10] = ["Detroit Pistons", "Pistons", True, "DetroitPistons.png"]
NBATeamDict[11] = ["Golden State Warriors", "Warriors", False, "GoldenStateWarriors.png"]
NBATeamDict[14] = ["Houston Rockets", "Rockets", False, "HoustonRockets.png"]
NBATeamDict[15] = ["Indiana Pacers", "Pacers", True, "IndianaPacers.png"]
NBATeamDict[16] = ["Los Angeles Clippers", "Clippers", False, "LosAngelesClippers.png"]
NBATeamDict[17] = ["Los Angeles Lakers", "Lakers", False, "LosAngelesLakers.png"]
NBATeamDict[19] = ["Memphis Grizzlies", "Grizzlies", False, "MemphisGrizzlies.png"]
NBATeamDict[20] = ["Miami Heat", "Heat", True, "MiamiHeat.png"]
NBATeamDict[21] = ["Milwaukee Bucks", "Bucks", True, "MilwaukeeBucks.png"]
NBATeamDict[22] = ["Minnesota Timberwolves", "Timberwolves", False, "MinnesotaTimberwolves.png"]
NBATeamDict[23] = ["New Orleans Pelicans", "Pelicans", False, "NewOrleansPelicans.png"]
NBATeamDict[24] = ["New York Knicks", "Knicks", True, "NewYorkKnicks.png"]
NBATeamDict[25] = ["Oklahoma City Thunder", "Thunder", False, "OklahomaCityThunder.png"]
NBATeamDict[26] = ["Orlando Magic", "Magic", True, "OrlandoMagic.png"]
NBATeamDict[27] = ["Philadelphia 76ers", "76ers", True, "Philadelphia76ers.png"]
NBATeamDict[28] = ["Phoenix Suns", "Suns", False, "PhoenixSuns.png"]
NBATeamDict[29] = ["Portland Trailblazers", "Trailblazers", False, "PortlandTrailblazers.png"]
NBATeamDict[30] = ["Sacramento Kings", "Kings", False, "SacramentoKings.png"]
NBATeamDict[31] = ["San Antonio Spurs", "Spurs", False, "San AntonioSpurs.png"]
NBATeamDict[38] = ["Toronto Raptors", "Raptors", True, "TorontoRaptors.png"]
NBATeamDict[40] = ["Utah Jazz", "Jazz", False, "UtahJazz.png"]
NBATeamDict[41] = ["Washington Wizards", "Wizards", True, "WashingtonWizards.png"]
