

NBATeamDict = {}

NBATeamDict[1] = ["Atlanta Hawks", "Hawks", True, "Atlanta Hawks.png"]
NBATeamDict[2] = ["Boston Celtics", "Celtics", True, "Boston Celtics.png"]
NBATeamDict[4] = ["Brooklyn Nets", "Nets", True, "Brooklyn Nets.png"]
NBATeamDict[5] = ["Charlotte Hornets", "Hornets", True, "Charlotte Hornets.png"]
NBATeamDict[6] = ["Chicago Bulls", "Bulls", True, "Chicago Bulls.png"]
NBATeamDict[7] = ["Cleveland Cavaliers", "Cavaliers", True, "Cleveland Cavaliers.png"]
NBATeamDict[8] = ["Dallas Mavericks", "Mavericks", False, "Dallas Mavericks.png"]
NBATeamDict[9] = ["Denver Nuggets", "Nuggets", False, "Denver Nuggets.png"]
NBATeamDict[10] = ["Detroit Pistons", "Pistons", True, "Detroit Pistons.png"]
NBATeamDict[11] = ["Golden State Warriors", "Warriors", False, "Golden State Warriors.png"]
NBATeamDict[14] = ["Houston Rockets", "Rockets", False, "Houston Rockets.png"]
NBATeamDict[15] = ["Indiana Pacers", "Pacers", True, "Indiana Pacers.png"]
NBATeamDict[16] = ["Los Angeles Clippers", "Clippers", False, "Los Angeles Clippers.png"]
NBATeamDict[17] = ["Los Angeles Lakers", "Lakers", False, "Los Angeles Lakers.png"]
NBATeamDict[19] = ["Memphis Grizzlies", "Grizzlies", False, "Memphis Grizzlies.png"]
NBATeamDict[20] = ["Miami Heat", "Heat", True, "Miami Heat.png"]
NBATeamDict[21] = ["Milwaukee Bucks", "Bucks", True, "Milwaukee Bucks.png"]
NBATeamDict[22] = ["Minnesota Timberwolves", "Timberwolves", False, "Minnesota TImberwolves.png"]
NBATeamDict[23] = ["New Orleans Pelicans", "Pelicans", False, "New Orleans Pelicans.png"]
NBATeamDict[24] = ["New York Knicks", "Knicks", True, "New York Knicks.png"]
NBATeamDict[25] = ["Oklahoma City Thunder", "Thunder", False, "Oklahoma City Thunder.png"]
NBATeamDict[26] = ["Orlando Magic", "Magic", True, "Orlando Magic.png"]
NBATeamDict[27] = ["Philadelphia 76ers", "76ers", True, "Philadelphia 76ers.png"]
NBATeamDict[28] = ["Phoenix Suns", "Suns", False, "Phoenix Suns.png"]
NBATeamDict[29] = ["Portland Trailblazers", "Trailblazers", False, "Portland Trailblazers.png"]
NBATeamDict[30] = ["Sacramento Kings", "Kings", False, "Sacramento Kings.png"]
NBATeamDict[31] = ["San Antonio Spurs", "Spurs", False, "San Antonio Spurs.png"]
NBATeamDict[38] = ["Toronto Raptors", "Raptors", True, "Toronto Raptors.png"]
NBATeamDict[40] = ["Utah Jazz", "Jazz", False, "Utah Jazz.png"]
NBATeamDict[41] = ["Washington Wizards", "Wizards", True, "Washington Wizards.png"]
